version: "3.9"
services:
    mtproto:
        container_name: mtproto
        image: 0xlem0nade/mtprotopy:latest
        restart: always
        networks:
            - caddy
        expose:
            - 5443
        volumes:
            - $HOME/Docker/mtproto/config/config.toml:/config/config.toml:ro
            - $HOME/Docker/mtproto/config/users.toml:/config/users.toml:ro
            - $HOME/Docker/mtproto/client/:/client
        logging:
            driver: "json-file"
            options:
                max-file: "1"
                max-size: "10m"

networks:
    caddy:
        external: true
