version: "3.9"

services:
  blocky:
    image: spx01/blocky:latest
    restart: always
    container_name: blocky
    user: 0:0
    cap_add:
      - CAP_NET_BIND_SERVICE
      - CAP_NET_RAW
    networks:
      - caddy
    ports:
      - "53:53"
      - "53:53/udp"
    environment:
      - TZ=UTC
    volumes:
      - /var/log:/logs
      - $HOME/Docker/blocky/etc/config.yml:/app/config.yml

networks:
  caddy:
    external: true
